### ISSUE TITLE
Is it possible to exclude path parameters from a route?

### ISSUE THREAD

**Issue by AntoineAA** [wraithgar/hapi-rate-limit#122]
Hello,

First, thank you for this very useful plugin!

Here is the last thing I can't do with the current configuration options.
I'm using "per route" configuration with the following options :

```
routes: {
	method: 'GET',
	path:'/v1/test/rate_limiter/{id}',
	handler: (request, h) => {
		//
	},
	config: {
		plugins: {
			'hapi-rate-limit': {
				enabled: true,
				userPathLimit: 5,
				userPathCache: {
					expiresIn: 60 * 1000
				}
			}
		}
	}
}
```

Currently, I can call `/v1/test/rate_limiter/18` 5 times and `/v1/test/rate_limiter/19` 5 times.
I would like to exclude the `id` parameter from the limiter (or be able to set the unique path key for this route) to limit to 5 calls of `/v1/test/rate_limiter/*`. In this example, the key might be `v1_test_rate_limiter`.

Is that possible?

**Comment by wraithgar** [comment]
No it's not currently possible. It seems like a worthwhile addition and I would be happy to discuss/design that feature but I would not have the time to implement it right now.
