### ISSUE TITLE
Value of x-ratelimit-userreset is a date string instead of number of seconds

### ISSUE THREAD

**Issue by claaslange** [wraithgar/hapi-rate-limit#18]
Hi,

I noticed the documentation in the readme and the actual behavior of the plugin differ.

The documentation says:

> Response Headers
> 
> The following headers will be included in server responses if their respective limits are enabled
> 
> x-ratelimit-pathlimit: Will equal pathLimit
> x-ratelimit-pathremaining: Remaining number of requests path has this - period
> x-ratelimit-pathreset: Time (in seconds) until reset of pathLimit period
> x-ratelimit-userlimit: Will equal userLimit
> x-ratelimit-userremaining: Remaining number of requests user has this period
> x-ratelimit-userreset: Time (in seconds) until reset of userLimit period

I however get a date string back in the header. I'd prefer to get back the number of seconds till the next reset happens.

And while we're on the topic of the header names. I'd like to have the option to choose my own names for the header fields. Would you be open towards a pull request, which adds this feature?

**Comment by wraithgar** [comment]
Hello! Are you referring to the pathreset and userreset headers?  I believe what I was trying to do there was return in UTC seconds. The behavior of the headers was patterned after github's https://developer.github.com/v3/#rate-limiting

I think I would prefer fixing it to be like that (casting the date object as integer effectively).

The behavior described in the readme (seconds till reset) could also be returned. I fear we're potentially getting a little out there in the headers returned (or is it just me) and as such having them customizable both in name and presence (i.e. which headers should be returned) would be a very welcome pull request.  I would humbly suggest that the header that represents the remaining time in seconds end in `ttl`.

Thanks for your bug report and feedback!  It's very much appreciated that you took the time to make this issue, and any effort you made towards the described PR would be also appreciated, and welcome.

**Comment by wraithgar** [comment]
I made a PR to fix the headers and update the readme here https://github.com/wraithgar/hapi-rate-limit/pull/19

**Comment by wraithgar** [comment]
I don't know if you'd also started on that part of this issue too, if you have we can totally disregard my PR and wait on yours.

**Comment by claaslange** [comment]
If you want to return the timestamp thats totally fine for me, go ahed and merge it. For our use case I needed to modify the plugin a little bit further, since we don't want to fail, if the cache is unavailable, so my changes are not completely compatible with this repository. I hope I'll find some time today extract my changes that allow the header names to be configurable. Will create a PR then :)
