### ISSUE TITLE
Support for captcha bypass

### ISSUE THREAD

**Issue by fraviemor** [wraithgar/hapi-rate-limit#32]
New feature:
Check with a captcha validation. For example Google ReCaptcha: https://developers.google.com/recaptcha/intro

If remaining tries are lower than 0 and the request contains captcha code, call Google reCaptcha API. If the response is true (validation success), bypass rate limit for this request.

Could be added this feature?

**Comment by wraithgar** [comment]
As described this seems to me to be outside the scope of this module.

I thing more generically there could be some mechanism by which the module allows you to register code to determine whether or not to rate limit a route.  I have no idea what that would look like though.  If you do I'd definitely love to discuss it.

**Comment by FraVieMor** [comment]
Yes, could be a solution. Include a handler by which it allows bypass the rate limit. 
In this handler I could implement the recaptcha validation or any other functionality.

Tell me if you know how implement this. I'll have a look too.
