### ISSUE TITLE
Increase number of tries for certain response codes

### ISSUE THREAD

**Issue by Cheprer** [wraithgar/hapi-rate-limit#34]
Hey just idea for nice feature:

It would be nice if the counter would increase only for specified responses. Like when it is 400 or 403 it would count them and not for 200. This could prevent brute force attacks when someone is trying to guess. Dunno if its possible, maybe I'll take a look at the code myself. For now I would need to implement it somewhere around hapi-auth-jwt2 and it's callbacks.

Cheers

**Comment by wraithgar** [comment]
Doing this would require the issues in #33 to be addressed first, then this module would be running before your auth plugin and could do this kind of check.

As far as the config, a sensible way to define the range of codes to accept would need to be added.

**Comment by Cheprer** [comment]
I've added this to count in not authorized request when trying to guess the guess security token or whatever it is in the header to check it, like jwt etc. With this I can use this tool completely to prevent brute force attacks.

I've added this limit per user and it overrides enabled option because if you want to count just 401s and not the other responses.

**Comment by wraithgar** [comment]
I added a comment in that PR outlining my thoughts and also why this is going to be difficult to address especially in re the part you mentioned about brute-forcing the authorization.

**Comment by wraithgar** [comment]
Brute forcing auth is its own issue #77
