### ISSUE TITLE
hapi in cluster mode

### ISSUE THREAD

**Issue by AntoineAA** [wraithgar/hapi-rate-limit#52]
Hi,

Thank you for this plugin, really useful!

I'm using hapi in cluster mode with pm2.
In this mode, rate limits are applied to each instance and not for the whole server.
If I start only one instance, it works good.

Do you have any tips for getting around the problem?

Best,
Antoine

**Comment by AntoineAA** [comment]
I did some tests, and I do not see `set` operation in redis for this plugin (`redis-cli monitor`).
I'm using catbox-redis.

**Comment by wraithgar** [comment]
Are you telling each hapi to use the same cache?

The line in the example from the readme is

```js
const server = Hapi.server({
    cache: { engine: require('catbox-memory'), name: 'memory' }
});
```

But you'd want to change that to catbox-redis and configure it to use the same redis instance.  Under the hood it calls the `cache` method on the server, so whatever the server has as its cache is used.

More info on setting that up can be found in the [hapi docs](https://hapijs.com/api#-serveroptionscache)

**Comment by AntoineAA** [comment]
This is the current setup:

```javascript
const Hapi = require('hapi'); // 17.5.3
const CatboxRedis = require('catbox-redis'); // 4.2.0 ("catbox": "^10.0.2")
const HapiRateLimiter = require('hapi-rate-limit'); // 2.1.2

const server = new Hapi.Server({
	host: env.host,
	port: env.port,
	cache: {
		name: env.cache.redisName,
		engine: CatboxRedis,
		host: env.cache.redisHost,
		partition: env.cache.redisPartition
	}
});
...
await server.register({
	plugin: HapiRateLimiter,
	options: {
		enabled: env.rateLimiter.enabled,
		userLimit: false,
		pathLimit: false,
		userPathLimit: false,
		ipWhitelist: env.rateLimiter.ipWhitelist,
		trustProxy: true
	}
});
```

A test route:

```javascript
{
	method: 'GET',
	path:'/v1/test/rate_limiter',
	handler: (request, h) => {
			return { test: 'it works, baby!' };
	},
	config: {
		plugins: {
			'hapi-rate-limit': {
				enabled: true,
				userPathLimit: 5,
				userPathCache: {
					expiresIn: 86400000
				}
			}
		}
	}
}
```

With this example, I don't see any read / write operations in Redis. The rate limiter works in single instance, it restarts at 0 if I restart the server (in memory, I guess).

Redis cache (content cache) works fine in cluster mode, here an example:

```javascript
options: {
	cache: {
		cache: env.cache.redisName,
		expiresIn: env.cache.expiresIn.oneDay,
		generateTimeout: env.cache.timeout,
		getDecoratedValue: true
	},
	generateKey: (...) => {
		...
	}
}
```

**Comment by wraithgar** [comment]
The hapi docs say that the cache a plugin will use defaults to the global one.  Since this appears not to be working I don't know, Perhaps you can add the server cache instance to the userPathCache config, since that is a valid parameter catbox accept.s

This isn't something I'm going to be able to debug myself, this is mostly a hobby project and I don't have a lot of free time for much more than the greenkeeper maintenance on it.

**Comment by AntoineAA** [comment]
Hi @wraithgar,

If I replace this:
```
const server = new Hapi.Server({
	host: env.host,
	port: env.port,
	cache: {
		name: env.cache.redisName,
		engine: require('catbox-redis'),
		host: env.cache.redisHost,
		partition: env.cache.redisPartition
	}
});
```
by this code:
```
const server = new Hapi.Server({
	host: env.host,
	port: env.port,
	cache: require('catbox-redis')
});
```
it works!
