### ISSUE TITLE
Update out of date dependencies

### ISSUE THREAD

**Issue by jrpedrianes** [wraithgar/hapi-rate-limit#67]
npm WARN deprecated boom@7.3.0: This module has moved and is now available at @hapi/boom. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.

npm WARN deprecated joi@14.3.1: This module has moved and is now available at @hapi/joi. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.

**Comment by wraithgar** [comment]
Fixed in `v3.1.3`
